2020-09-22 20:36:59,000 -  nornir.core -     INFO -        run() - Running task 'configure_probes' with args {'xml_config': '<?xml version="1.0" encoding="utf-8"?>\n<config>\n\t<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">\n\t\t<ip>\n\t\t\t<sla xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-sla" operation="replace">\n\t\t\t\t<responder></responder>\n\t\t\t\t<entry>\n\t\t\t\t\t<number>101</number>\n\t\t\t\t\t<udp-jitter>\n\t\t\t\t\t\t<dest-addr>10.0.0.101</dest-addr>\n\t\t\t\t\t\t<portno>16384</portno>\n\t\t\t\t\t\t<num-packets>20</num-packets>\n\t\t\t\t\t\t<interval>15</interval>\n\t\t\t\t\t\t<frequency>10</frequency>\n\t\t\t\t\t\t<timeout>2000</timeout>\n\t\t\t\t\t\t<tos>184</tos>\n\t\t\t\t\t\t<verify-data>true</verify-data>\n\t\t\t\t\t</udp-jitter>\n\t\t\t\t</entry>\n\t\t\t\t<schedule>\n\t\t\t\t\t<entry-number>101</entry-number>\n\t\t\t\t\t<life>forever</life>\n\t\t\t\t\t<start-time>\n\t\t\t\t\t\t<now-config></now-config>\n\t\t\t\t\t\t<now></now>\n\t\t\t\t\t</start-time>\n\t\t\t\t</schedule>\n\t\t\t</sla>\n\t\t</ip>\n\t</native>\n</config>'} on 1 hosts
2020-09-22 20:36:59,001 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'configure_probes' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "edit_config.py", line 18, in configure_probes
    conn = task.host.get_connection("netconf", task.nornir.config)
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/nornir/core/inventory.py", line 448, in get_connection
    extras=conn.extras,
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/nornir/core/inventory.py", line 481, in open_connection
    plugin = ConnectionPluginRegister.get_plugin(conn_name)
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/nornir/core/plugins/register.py", line 75, in get_plugin
    raise PluginNotRegistered(f"plugin {name!r} is not registered")
nornir.core.exceptions.PluginNotRegistered: plugin 'netconf' is not registered

2020-09-22 20:38:27,527 -  nornir.core -     INFO -        run() - Running task 'configure_probes' with args {'xml_config': '<?xml version="1.0" encoding="utf-8"?>\n<config>\n\t<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">\n\t\t<ip>\n\t\t\t<sla xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-sla" operation="replace">\n\t\t\t\t<responder></responder>\n\t\t\t\t<entry>\n\t\t\t\t\t<number>101</number>\n\t\t\t\t\t<udp-jitter>\n\t\t\t\t\t\t<dest-addr>10.0.0.101</dest-addr>\n\t\t\t\t\t\t<portno>16384</portno>\n\t\t\t\t\t\t<num-packets>20</num-packets>\n\t\t\t\t\t\t<interval>15</interval>\n\t\t\t\t\t\t<frequency>10</frequency>\n\t\t\t\t\t\t<timeout>2000</timeout>\n\t\t\t\t\t\t<tos>184</tos>\n\t\t\t\t\t\t<verify-data>true</verify-data>\n\t\t\t\t\t</udp-jitter>\n\t\t\t\t</entry>\n\t\t\t\t<schedule>\n\t\t\t\t\t<entry-number>101</entry-number>\n\t\t\t\t\t<life>forever</life>\n\t\t\t\t\t<start-time>\n\t\t\t\t\t\t<now-config></now-config>\n\t\t\t\t\t\t<now></now>\n\t\t\t\t\t</start-time>\n\t\t\t\t</schedule>\n\t\t\t</sla>\n\t\t</ip>\n\t</native>\n</config>'} on 1 hosts
2020-09-22 20:38:27,528 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'configure_probes' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "edit_config.py", line 18, in configure_probes
    conn = task.host.get_connection("netconf", task.nornir.config)
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/nornir/core/inventory.py", line 448, in get_connection
    extras=conn.extras,
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/nornir/core/inventory.py", line 481, in open_connection
    plugin = ConnectionPluginRegister.get_plugin(conn_name)
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/nornir/core/plugins/register.py", line 75, in get_plugin
    raise PluginNotRegistered(f"plugin {name!r} is not registered")
nornir.core.exceptions.PluginNotRegistered: plugin 'netconf' is not registered

2020-09-22 20:38:35,609 -  nornir.core -     INFO -        run() - Running task 'configure_probes' with args {'xml_config': '<?xml version="1.0" encoding="utf-8"?>\n<config>\n\t<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">\n\t\t<ip>\n\t\t\t<sla xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-sla" operation="replace">\n\t\t\t\t<responder></responder>\n\t\t\t\t<entry>\n\t\t\t\t\t<number>101</number>\n\t\t\t\t\t<udp-jitter>\n\t\t\t\t\t\t<dest-addr>10.0.0.101</dest-addr>\n\t\t\t\t\t\t<portno>16384</portno>\n\t\t\t\t\t\t<num-packets>20</num-packets>\n\t\t\t\t\t\t<interval>15</interval>\n\t\t\t\t\t\t<frequency>10</frequency>\n\t\t\t\t\t\t<timeout>2000</timeout>\n\t\t\t\t\t\t<tos>184</tos>\n\t\t\t\t\t\t<verify-data>true</verify-data>\n\t\t\t\t\t</udp-jitter>\n\t\t\t\t</entry>\n\t\t\t\t<schedule>\n\t\t\t\t\t<entry-number>101</entry-number>\n\t\t\t\t\t<life>forever</life>\n\t\t\t\t\t<start-time>\n\t\t\t\t\t\t<now-config></now-config>\n\t\t\t\t\t\t<now></now>\n\t\t\t\t\t</start-time>\n\t\t\t\t</schedule>\n\t\t\t</sla>\n\t\t</ip>\n\t</native>\n</config>'} on 1 hosts
2020-09-22 20:38:43,429 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'configure_probes' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "edit_config.py", line 19, in configure_probes
    conn = task.host.get_connection("netconf", task.nornir.config)
  File "/usr/local/lib/python3.7/bdb.py", line 94, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/usr/local/lib/python3.7/bdb.py", line 174, in dispatch_exception
    if self.quitting: raise BdbQuit
bdb.BdbQuit

2020-09-22 20:43:58,966 -  nornir.core -     INFO -        run() - Running task 'configure_probes' with args {'xml_config': '<?xml version="1.0" encoding="utf-8"?>\n<config>\n\t<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">\n\t\t<ip>\n\t\t\t<sla xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-sla" operation="replace">\n\t\t\t\t<responder></responder>\n\t\t\t\t<entry>\n\t\t\t\t\t<number>101</number>\n\t\t\t\t\t<udp-jitter>\n\t\t\t\t\t\t<dest-addr>10.0.0.101</dest-addr>\n\t\t\t\t\t\t<portno>16384</portno>\n\t\t\t\t\t\t<num-packets>20</num-packets>\n\t\t\t\t\t\t<interval>15</interval>\n\t\t\t\t\t\t<frequency>10</frequency>\n\t\t\t\t\t\t<timeout>2000</timeout>\n\t\t\t\t\t\t<tos>184</tos>\n\t\t\t\t\t\t<verify-data>true</verify-data>\n\t\t\t\t\t</udp-jitter>\n\t\t\t\t</entry>\n\t\t\t\t<schedule>\n\t\t\t\t\t<entry-number>101</entry-number>\n\t\t\t\t\t<life>forever</life>\n\t\t\t\t\t<start-time>\n\t\t\t\t\t\t<now-config></now-config>\n\t\t\t\t\t\t<now></now>\n\t\t\t\t\t</start-time>\n\t\t\t\t</schedule>\n\t\t\t</sla>\n\t\t</ip>\n\t</native>\n</config>'} on 1 hosts
2020-09-22 20:44:26,067 -  nornir.core -     INFO -        run() - Running task 'configure_probes' with args {'xml_config': '<?xml version="1.0" encoding="utf-8"?>\n<config>\n\t<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">\n\t\t<ip>\n\t\t\t<sla xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-sla" operation="replace">\n\t\t\t\t<responder></responder>\n\t\t\t\t<entry>\n\t\t\t\t\t<number>101</number>\n\t\t\t\t\t<udp-jitter>\n\t\t\t\t\t\t<dest-addr>10.0.0.101</dest-addr>\n\t\t\t\t\t\t<portno>16384</portno>\n\t\t\t\t\t\t<num-packets>20</num-packets>\n\t\t\t\t\t\t<interval>15</interval>\n\t\t\t\t\t\t<frequency>10</frequency>\n\t\t\t\t\t\t<timeout>2000</timeout>\n\t\t\t\t\t\t<tos>184</tos>\n\t\t\t\t\t\t<verify-data>true</verify-data>\n\t\t\t\t\t</udp-jitter>\n\t\t\t\t</entry>\n\t\t\t\t<schedule>\n\t\t\t\t\t<entry-number>101</entry-number>\n\t\t\t\t\t<life>forever</life>\n\t\t\t\t\t<start-time>\n\t\t\t\t\t\t<now-config></now-config>\n\t\t\t\t\t\t<now></now>\n\t\t\t\t\t</start-time>\n\t\t\t\t</schedule>\n\t\t\t</sla>\n\t\t</ip>\n\t</native>\n</config>'} on 1 hosts
2020-09-22 20:51:27,615 -  nornir.core -     INFO -        run() - Running task 'configure_probes' with args {'xml_config': '<?xml version="1.0" encoding="utf-8"?>\n<config>\n\t<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">\n\t\t<ip>\n\t\t\t<sla xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-sla" operation="replace">\n\t\t\t\t<responder></responder>\n\t\t\t\t<entry>\n\t\t\t\t\t<number>101</number>\n\t\t\t\t\t<udp-jitter>\n\t\t\t\t\t\t<dest-addr>10.0.0.101</dest-addr>\n\t\t\t\t\t\t<portno>16384</portno>\n\t\t\t\t\t\t<num-packets>20</num-packets>\n\t\t\t\t\t\t<interval>30</interval>\n\t\t\t\t\t\t<frequency>30</frequency>\n\t\t\t\t\t\t<timeout>3000</timeout>\n\t\t\t\t\t\t<tos>184</tos>\n\t\t\t\t\t\t<verify-data>true</verify-data>\n\t\t\t\t\t</udp-jitter>\n\t\t\t\t</entry>\n\t\t\t\t<entry>\n\t\t\t\t\t<number>102</number>\n\t\t\t\t\t<udp-jitter>\n\t\t\t\t\t\t<dest-addr>10.0.0.102</dest-addr>\n\t\t\t\t\t\t<portno>16384</portno>\n\t\t\t\t\t\t<num-packets>20</num-packets>\n\t\t\t\t\t\t<interval>30</interval>\n\t\t\t\t\t\t<frequency>30</frequency>\n\t\t\t\t\t\t<timeout>3000</timeout>\n\t\t\t\t\t\t<tos>184</tos>\n\t\t\t\t\t\t<verify-data>true</verify-data>\n\t\t\t\t\t</udp-jitter>\n\t\t\t\t</entry>\n\t\t\t\t<schedule>\n\t\t\t\t\t<entry-number>101</entry-number>\n\t\t\t\t\t<life>forever</life>\n\t\t\t\t\t<start-time>\n\t\t\t\t\t\t<now-config></now-config>\n\t\t\t\t\t\t<now></now>\n\t\t\t\t\t</start-time>\n\t\t\t\t</schedule>\n\t\t\t\t<schedule>\n\t\t\t\t\t<entry-number>102</entry-number>\n\t\t\t\t\t<life>forever</life>\n\t\t\t\t\t<start-time>\n\t\t\t\t\t\t<now-config></now-config>\n\t\t\t\t\t\t<now></now>\n\t\t\t\t\t</start-time>\n\t\t\t\t</schedule>\n\t\t\t</sla>\n\t\t</ip>\n\t</native>\n</config>'} on 2 hosts
2020-09-22 20:51:29,542 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'configure_probes' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "edit_config.py", line 34, in configure_probes
    commit = conn.commit()
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/ncclient/manager.py", line 231, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/ncclient/operations/edit.py", line 164, in request
    return self._request(node)
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/ncclient/operations/rpc.py", line 360, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: inconsistent value: Device refused one or more commands

2020-09-22 20:51:30,233 - nornir.core.task -    ERROR -      start() - Host 'CSR2': task 'configure_probes' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "edit_config.py", line 34, in configure_probes
    commit = conn.commit()
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/ncclient/manager.py", line 231, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/ncclient/operations/edit.py", line 164, in request
    return self._request(node)
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/ncclient/operations/rpc.py", line 360, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: inconsistent value: Device refused one or more commands

2020-09-22 20:52:59,278 -  nornir.core -     INFO -        run() - Running task 'configure_probes' with args {'xml_config': '<?xml version="1.0" encoding="utf-8"?>\n<config>\n\t<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">\n\t\t<ip>\n\t\t\t<sla xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-sla" operation="replace">\n\t\t\t\t<responder></responder>\n\t\t\t\t<entry>\n\t\t\t\t\t<number>101</number>\n\t\t\t\t\t<udp-jitter>\n\t\t\t\t\t\t<dest-addr>10.0.0.101</dest-addr>\n\t\t\t\t\t\t<portno>16384</portno>\n\t\t\t\t\t\t<num-packets>20</num-packets>\n\t\t\t\t\t\t<interval>30</interval>\n\t\t\t\t\t\t<frequency>30</frequency>\n\t\t\t\t\t\t<timeout>3000</timeout>\n\t\t\t\t\t\t<tos>184</tos>\n\t\t\t\t\t\t<verify-data>true</verify-data>\n\t\t\t\t\t</udp-jitter>\n\t\t\t\t</entry>\n\t\t\t\t<schedule>\n\t\t\t\t\t<entry-number>101</entry-number>\n\t\t\t\t\t<life>forever</life>\n\t\t\t\t\t<start-time>\n\t\t\t\t\t\t<now-config></now-config>\n\t\t\t\t\t\t<now></now>\n\t\t\t\t\t</start-time>\n\t\t\t\t</schedule>\n\t\t\t</sla>\n\t\t</ip>\n\t</native>\n</config>'} on 1 hosts
2020-09-22 20:53:32,048 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'configure_probes' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "edit_config.py", line 35, in configure_probes
    commit = conn.commit()
  File "/usr/local/lib/python3.7/bdb.py", line 94, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/usr/local/lib/python3.7/bdb.py", line 174, in dispatch_exception
    if self.quitting: raise BdbQuit
bdb.BdbQuit

2020-09-22 20:54:28,572 -  nornir.core -     INFO -        run() - Running task 'configure_probes' with args {'xml_config': '<?xml version="1.0" encoding="utf-8"?>\n<config>\n\t<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">\n\t\t<ip>\n\t\t\t<sla xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-sla" operation="replace">\n\t\t\t\t<responder></responder>\n\t\t\t\t<entry>\n\t\t\t\t\t<number>101</number>\n\t\t\t\t\t<udp-jitter>\n\t\t\t\t\t\t<dest-addr>9.9.9.9</dest-addr>\n\t\t\t\t\t\t<portno>16384</portno>\n\t\t\t\t\t\t<num-packets>20</num-packets>\n\t\t\t\t\t\t<interval>30</interval>\n\t\t\t\t\t\t<frequency>30</frequency>\n\t\t\t\t\t\t<timeout>3000</timeout>\n\t\t\t\t\t\t<tos>184</tos>\n\t\t\t\t\t\t<verify-data>true</verify-data>\n\t\t\t\t\t</udp-jitter>\n\t\t\t\t</entry>\n\t\t\t\t<schedule>\n\t\t\t\t\t<entry-number>101</entry-number>\n\t\t\t\t\t<life>forever</life>\n\t\t\t\t\t<start-time>\n\t\t\t\t\t\t<now-config></now-config>\n\t\t\t\t\t\t<now></now>\n\t\t\t\t\t</start-time>\n\t\t\t\t</schedule>\n\t\t\t</sla>\n\t\t</ip>\n\t</native>\n</config>'} on 1 hosts
2020-09-22 20:54:48,508 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'configure_probes' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "edit_config.py", line 35, in configure_probes
    commit = conn.commit()
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/ncclient/manager.py", line 231, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/ncclient/operations/edit.py", line 164, in request
    return self._request(node)
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/ncclient/operations/rpc.py", line 360, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: inconsistent value: Device refused one or more commands

2020-09-22 20:55:21,431 -  nornir.core -     INFO -        run() - Running task 'configure_probes' with args {'xml_config': '<?xml version="1.0" encoding="utf-8"?>\n<config>\n\t<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">\n\t\t<ip>\n\t\t\t<sla xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-sla" operation="replace">\n\t\t\t\t<responder></responder>\n\t\t\t\t<entry>\n\t\t\t\t\t<number>101</number>\n\t\t\t\t\t<udp-jitter>\n\t\t\t\t\t\t<dest-addr>9.9.9.9</dest-addr>\n\t\t\t\t\t\t<portno>16384</portno>\n\t\t\t\t\t\t<num-packets>20</num-packets>\n\t\t\t\t\t\t<interval>30</interval>\n\t\t\t\t\t\t<frequency>30</frequency>\n\t\t\t\t\t\t<timeout>3000</timeout>\n\t\t\t\t\t\t<tos>184</tos>\n\t\t\t\t\t\t<verify-data>true</verify-data>\n\t\t\t\t\t</udp-jitter>\n\t\t\t\t</entry>\n\t\t\t\t<schedule>\n\t\t\t\t\t<entry-number>101</entry-number>\n\t\t\t\t\t<life>forever</life>\n\t\t\t\t\t<start-time>\n\t\t\t\t\t\t<now-config></now-config>\n\t\t\t\t\t\t<now></now>\n\t\t\t\t\t</start-time>\n\t\t\t\t</schedule>\n\t\t\t</sla>\n\t\t</ip>\n\t</native>\n</config>'} on 1 hosts
2020-09-22 20:55:23,473 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'configure_probes' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "edit_config.py", line 23, in configure_probes
    config_resp = conn.edit_config(
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/ncclient/manager.py", line 231, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/ncclient/operations/edit.py", line 164, in request
    return self._request(node)
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/ncclient/operations/rpc.py", line 360, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: inconsistent value: Device refused one or more commands

2020-09-22 21:01:31,703 -  nornir.core -     INFO -        run() - Running task 'configure_probes' with args {'xml_config': '<?xml version="1.0" encoding="utf-8"?>\n<config>\n\t<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">\n\t\t<ip>\n\t\t\t<sla xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-sla" operation="replace">\n\t\t\t\t<responder></responder>\n\t\t\t\t<entry>\n\t\t\t\t\t<number>101</number>\n\t\t\t\t\t<udp-jitter>\n\t\t\t\t\t\t<dest-addr>10.0.0.101</dest-addr>\n\t\t\t\t\t\t<portno>16384</portno>\n\t\t\t\t\t\t<num-packets>20</num-packets>\n\t\t\t\t\t\t<interval>30</interval>\n\t\t\t\t\t\t<frequency>30</frequency>\n\t\t\t\t\t\t<timeout>3000</timeout>\n\t\t\t\t\t\t<tos>184</tos>\n\t\t\t\t\t\t<verify-data>true</verify-data>\n\t\t\t\t\t</udp-jitter>\n\t\t\t\t</entry>\n\t\t\t\t<schedule>\n\t\t\t\t\t<entry-number>101</entry-number>\n\t\t\t\t\t<life>forever</life>\n\t\t\t\t\t<start-time>\n\t\t\t\t\t\t<now-config></now-config>\n\t\t\t\t\t\t<now></now>\n\t\t\t\t\t</start-time>\n\t\t\t\t</schedule>\n\t\t\t</sla>\n\t\t</ip>\n\t</native>\n</config>'} on 1 hosts
2020-09-22 21:01:46,523 - nornir.core.task -    ERROR -      start() - Host 'CSR1': task 'configure_probes' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "edit_config.py", line 35, in configure_probes
    commit = conn.commit()
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/ncclient/manager.py", line 231, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/ncclient/operations/edit.py", line 164, in request
    return self._request(node)
  File "/home/centos/environments/nsla/lib/python3.7/site-packages/ncclient/operations/rpc.py", line 360, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: inconsistent value: Device refused one or more commands

